package Model;
// Generated May 11, 2020 3:54:05 PM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String regid;
     private String firstname;
     private String lastname;
     private String phonenumber;
     private String emailaddress;
     private String clientcategory;
     private String image;

    public Client() {
    }

	
    public Client(String regid) {
        this.regid = regid;
    }
    public Client(String regid, String firstname, String lastname, String phonenumber, String emailaddress, String clientcategory, String image) {
       this.regid = regid;
       this.firstname = firstname;
       this.lastname = lastname;
       this.phonenumber = phonenumber;
       this.emailaddress = emailaddress;
       this.clientcategory = clientcategory;
       this.image = image;
    }
   
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public String getEmailaddress() {
        return this.emailaddress;
    }
    
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }
    public String getClientcategory() {
        return this.clientcategory;
    }
    
    public void setClientcategory(String clientcategory) {
        this.clientcategory = clientcategory;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


